"""empty message

Revision ID: 14a258d52dda
Revises: fa5949db6b87
Create Date: 2017-04-20 13:25:37.694043

"""

# revision identifiers, used by Alembic.
revision = '14a258d52dda'
down_revision = 'fa5949db6b87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_location', sa.Column('external_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_location', 'external_port')
    # ### end Alembic commands ###
