"""empty message

Revision ID: 1506653d49f6
Revises: 2e74aba94b64
Create Date: 2016-11-11 13:04:12.062555

"""

# revision identifiers, used by Alembic.
revision = '1506653d49f6'
down_revision = '2e74aba94b64'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_subscriber_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_subscriber_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(length=200), nullable=True),
    sa.Column('longitude', sa.String(length=200), nullable=True),
    sa.Column('gmtoff', sa.String(length=200), nullable=True),
    sa.Column('dstoff', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_subscriber_id'], ['list_subscriber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'list_subscriber', 'timestamp_signup')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'list_subscriber', sa.Column('timestamp_signup', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('list_subscriber_location')
    ### end Alembic commands ###
