"""empty message

Revision ID: 15c856b95850
Revises: 2e024608ea28
Create Date: 2016-10-27 11:59:14.052923

"""

# revision identifiers, used by Alembic.
revision = '15c856b95850'
down_revision = '2e024608ea28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isadmin', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isadmin')
    ### end Alembic commands ###
