"""empty message

Revision ID: 165a1f2d1cb7
Revises: 1df19cbe634c
Create Date: 2016-12-22 14:12:55.602587

"""

# revision identifiers, used by Alembic.
revision = '165a1f2d1cb7'
down_revision = '1df19cbe634c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_view_bounce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('unique_email_id', sa.String(length=200), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('campaign_title', sa.String(length=200), nullable=True),
    sa.Column('bounce_type', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_view_click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('unique_email_id', sa.String(length=200), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('campaign_title', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_view_open',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('unique_email_id', sa.String(length=200), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('campaign_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_view_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('unique_email_id', sa.String(length=200), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('campaign_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_view_unsubscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('unique_email_id', sa.String(length=200), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('campaign_title', sa.String(length=200), nullable=True),
    sa.Column('unsubscribe_type', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'list', sa.Column('campaign_last_sent', sa.TIMESTAMP(), nullable=True))
    op.drop_column(u'list_subscriber_activity', 'updated')
    op.drop_column(u'list_subscriber_activity', 'updated_by')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'list_subscriber_activity', sa.Column('updated_by', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column(u'list_subscriber_activity', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column(u'list', 'campaign_last_sent')
    op.drop_table('data_view_unsubscribe')
    op.drop_table('data_view_sent')
    op.drop_table('data_view_open')
    op.drop_table('data_view_click')
    op.drop_table('data_view_bounce')
    ### end Alembic commands ###
