"""empty message

Revision ID: 1940737b99e1
Revises: 4c0484b04d4c
Create Date: 2016-11-17 21:45:06.951861

"""

# revision identifiers, used by Alembic.
revision = '1940737b99e1'
down_revision = '4c0484b04d4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_category', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'template_category', 'brand', ['brand_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_category', type_='foreignkey')
    op.drop_column('template_category', 'brand_id')
    ### end Alembic commands ###
