"""empty message

Revision ID: 1981b84e7308
Revises: None
Create Date: 2016-10-27 11:44:53.258730

"""

# revision identifiers, used by Alembic.
revision = '1981b84e7308'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
