"""empty message

Revision ID: 1a88c3ecf0d0
Revises: 2ad2085188d
Create Date: 2016-11-09 11:04:26.988333

"""

# revision identifiers, used by Alembic.
revision = '1a88c3ecf0d0'
down_revision = '2ad2085188d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_merge_field_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_merge_field_id', sa.Integer(), nullable=True),
    sa.Column('choice', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_merge_field_id'], ['list_merge_field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'list_merge_field', sa.Column('date_format', sa.String(length=50), nullable=True))
    op.add_column(u'list_merge_field', sa.Column('default_country', sa.String(length=5), nullable=True))
    op.add_column(u'list_merge_field', sa.Column('phone_format', sa.String(length=50), nullable=True))
    op.add_column(u'list_merge_field', sa.Column('size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'list_merge_field', 'size')
    op.drop_column(u'list_merge_field', 'phone_format')
    op.drop_column(u'list_merge_field', 'default_country')
    op.drop_column(u'list_merge_field', 'date_format')
    op.drop_table('list_merge_field_choice')
    ### end Alembic commands ###
