"""empty message

Revision ID: 1b6a9c3796d7
Revises: 1b8776f5880b
Create Date: 2016-11-01 15:27:26.514605

"""

# revision identifiers, used by Alembic.
revision = '1b6a9c3796d7'
down_revision = '1b8776f5880b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('fieldset_on_form', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('create', sa.Boolean(), nullable=True),
    sa.Column('update', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('field_type', sa.String(length=20), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['form_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_field_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['form_field_id'], ['form_field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_field_option')
    op.drop_table('form_field')
    op.drop_table('form_group')
    ### end Alembic commands ###
