"""empty message

Revision ID: 1b8776f5880b
Revises: b5187f1704
Create Date: 2016-10-28 08:48:25.156556

"""

# revision identifiers, used by Alembic.
revision = '1b8776f5880b'
down_revision = 'b5187f1704'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_subscriber_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_subscriber_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_subscriber_id'], ['list_subscriber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'list', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column(u'list', sa.Column('mailchimp_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'list', 'folder', ['folder_id'], ['id'])
    op.add_column(u'list_subscriber', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column(u'list_subscriber', sa.Column('timestamp_signup', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'list_subscriber', 'brand', ['brand_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list_subscriber', type_='foreignkey')
    op.drop_column(u'list_subscriber', 'timestamp_signup')
    op.drop_column(u'list_subscriber', 'brand_id')
    op.drop_constraint(None, 'list', type_='foreignkey')
    op.drop_column(u'list', 'mailchimp_id')
    op.drop_column(u'list', 'folder_id')
    op.drop_table('list_subscriber_activity')
    ### end Alembic commands ###
