"""empty message

Revision ID: 1b9b40937513
Revises: 3b4b3483e5b0
Create Date: 2016-12-21 13:07:44.096850

"""

# revision identifiers, used by Alembic.
revision = '1b9b40937513'
down_revision = '3b4b3483e5b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('unique_opens', sa.Integer(), nullable=True),
    sa.Column('recipient_clicks', sa.Integer(), nullable=True),
    sa.Column('hard_bounce', sa.Integer(), nullable=True),
    sa.Column('soft_bounce', sa.Integer(), nullable=True),
    sa.Column('subs', sa.Integer(), nullable=True),
    sa.Column('unsubs', sa.Integer(), nullable=True),
    sa.Column('other_adds', sa.Integer(), nullable=True),
    sa.Column('other_removes', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'list_subscriber_activity', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.add_column(u'list_subscriber_activity', sa.Column('parent_campaign', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'list_subscriber_activity', 'campaign', ['parent_campaign'], ['id'])
    op.create_foreign_key(None, 'list_subscriber_activity', 'campaign', ['campaign_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list_subscriber_activity', type_='foreignkey')
    op.drop_constraint(None, 'list_subscriber_activity', type_='foreignkey')
    op.drop_column(u'list_subscriber_activity', 'parent_campaign')
    op.drop_column(u'list_subscriber_activity', 'campaign_id')
    op.drop_table('list_activity')
    ### end Alembic commands ###
