"""empty message

Revision ID: 1fdab9989a6f
Revises: 1b9b40937513
Create Date: 2016-12-21 13:10:29.045458

"""

# revision identifiers, used by Alembic.
revision = '1fdab9989a6f'
down_revision = '1b9b40937513'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
