"""empty message

Revision ID: 212739a64e07
Revises: 1fdab9989a6f
Create Date: 2016-12-21 13:13:21.107432

"""

# revision identifiers, used by Alembic.
revision = '212739a64e07'
down_revision = '1fdab9989a6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
