"""empty message

Revision ID: 21bf59883e1f
Revises: 360f3d20ca94
Create Date: 2017-01-14 13:31:38.834878

"""

# revision identifiers, used by Alembic.
revision = '21bf59883e1f'
down_revision = '360f3d20ca94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_export_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_delimiter', sa.String(length=1), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_activity', sa.String(length=20), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('system_definition', sa.Boolean(), nullable=True),
    sa.Column('notify_addresses', sa.String(length=1024), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['tracking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_export_actvity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_export_definition_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['tracking_export_definition_id'], ['tracking_export_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_export_actvity')
    op.drop_table('tracking_export_definition')
    ### end Alembic commands ###
