"""empty message

Revision ID: 227651992d0a
Revises: 1aa55fe45956
Create Date: 2016-12-30 11:01:18.072441

"""

# revision identifiers, used by Alembic.
revision = '227651992d0a'
down_revision = '1aa55fe45956'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variate_campaign_combination', sa.Column('recipients', sa.Integer(), nullable=True))
    op.drop_column('variate_campaign_combination', 'recipents')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variate_campaign_combination', sa.Column('recipents', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('variate_campaign_combination', 'recipients')
    ### end Alembic commands ###
