"""empty message

Revision ID: 2513dc22a5eb
Revises: 390f2b7a921a
Create Date: 2016-11-07 09:12:55.832452

"""

# revision identifiers, used by Alembic.
revision = '2513dc22a5eb'
down_revision = '390f2b7a921a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_actvity', sa.Column('errored', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_actvity', 'errored')
    ### end Alembic commands ###
