"""empty message

Revision ID: 25ebcd646361
Revises: 2ea1cccff689
Create Date: 2017-01-16 08:30:02.453558

"""

# revision identifiers, used by Alembic.
revision = '25ebcd646361'
down_revision = '2ea1cccff689'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('email_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'email_id')
    ### end Alembic commands ###
