"""empty message

Revision ID: 2603810e861d
Revises: 4a201ec909a7
Create Date: 2016-12-14 11:26:07.572251

"""

# revision identifiers, used by Alembic.
revision = '2603810e861d'
down_revision = '4a201ec909a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variate_campaign', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'variate_campaign', 'campaign', ['campaign_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variate_campaign', type_='foreignkey')
    op.drop_column('variate_campaign', 'campaign_id')
    ### end Alembic commands ###
