"""empty message

Revision ID: 292b23279f
Revises: 1506653d49f6
Create Date: 2016-11-15 10:24:11.610086

"""

# revision identifiers, used by Alembic.
revision = '292b23279f'
down_revision = '1506653d49f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
