"""empty message

Revision ID: 29e4a8ba81bc
Revises: 450ed2dc7f03
Create Date: 2016-11-29 14:46:39.209110

"""

# revision identifiers, used by Alembic.
revision = '29e4a8ba81bc'
down_revision = '450ed2dc7f03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailchimp_id', sa.String(length=50), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('match', sa.String(length=3), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('op', sa.String(length=50), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_subscriber',
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('list_subscriber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_subscriber_id'], ['list_subscriber.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_subscriber')
    op.drop_table('segment_condition')
    op.drop_table('segment')
    ### end Alembic commands ###
