"""empty message

Revision ID: 2ad2085188d
Revises: a27dc7418cb
Create Date: 2016-11-09 07:29:11.888685

"""

# revision identifiers, used by Alembic.
revision = '2ad2085188d'
down_revision = 'a27dc7418cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_merge_field', sa.Column('mailchimp_id', sa.Integer(), nullable=True))
    op.drop_column('list_subscriber_merge_field', 'mailchimp_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_subscriber_merge_field', sa.Column('mailchimp_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('list_merge_field', 'mailchimp_id')
    ### end Alembic commands ###
