"""empty message

Revision ID: 2b396187cfec
Revises: 66762a8fb29
Create Date: 2016-11-08 08:09:03.896713

"""

# revision identifiers, used by Alembic.
revision = '2b396187cfec'
down_revision = '66762a8fb29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('status_type', sa.String(length=50), nullable=True),
    sa.Column('response', sa.String(length=4000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_request_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_log_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('value', sa.String(length=4000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_log_id'], ['api_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_request_field')
    op.drop_table('api_log')
    ### end Alembic commands ###
