"""empty message

Revision ID: 2be0bf9a5fc2
Revises: 73820953f23
Create Date: 2016-12-29 11:59:13.640907

"""

# revision identifiers, used by Alembic.
revision = '2be0bf9a5fc2'
down_revision = '73820953f23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variate_campaign_combination', 'mailchimp_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variate_campaign_combination', sa.Column('mailchimp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    ### end Alembic commands ###
