"""empty message

Revision ID: 2c26bf6baff5
Revises: 3f94ae249f0f
Create Date: 2016-10-27 16:25:49.588307

"""

# revision identifiers, used by Alembic.
revision = '2c26bf6baff5'
down_revision = '3f94ae249f0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('permission_reminder', sa.String(length=1024), nullable=True),
    sa.Column('notify_on_subscribe', sa.String(length=200), nullable=True),
    sa.Column('notify_on_unsubscribe', sa.String(length=200), nullable=True),
    sa.Column('email_type_option', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=3), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_campaign_default',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('from_email', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('address2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('zip', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('unique_email_id', sa.String(length=200), nullable=True),
    sa.Column('email_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_subscriber_merge_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_subscriber_id', sa.Integer(), nullable=True),
    sa.Column('var', sa.String(length=200), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_subscriber_id'], ['list_subscriber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_subscriber_merge_field')
    op.drop_table('list_subscriber')
    op.drop_table('list_contact')
    op.drop_table('list_campaign_default')
    op.drop_table('list')
    ### end Alembic commands ###
