"""empty message

Revision ID: 2c7802e16388
Revises: 227651992d0a
Create Date: 2017-01-03 18:36:11.662028

"""

# revision identifiers, used by Alembic.
revision = '2c7802e16388'
down_revision = '227651992d0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('campaign_name', sa.String(length=200), nullable=True),
    sa.Column('email_name', sa.String(length=200), nullable=True),
    sa.Column('list_name', sa.String(length=200), nullable=True),
    sa.Column('segment_name', sa.String(length=200), nullable=True),
    sa.Column('send_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('subject_line', sa.String(length=200), nullable=True),
    sa.Column('number_sent', sa.Integer(), nullable=True),
    sa.Column('number_delivered', sa.Integer(), nullable=True),
    sa.Column('delivery_rate', sa.Float(), nullable=True),
    sa.Column('number_hard_bounces', sa.Integer(), nullable=True),
    sa.Column('percent_hard_bounces', sa.Float(), nullable=True),
    sa.Column('number_soft_bounces', sa.Integer(), nullable=True),
    sa.Column('percent_soft_bounces', sa.Float(), nullable=True),
    sa.Column('number_opens', sa.Integer(), nullable=True),
    sa.Column('percent_opens', sa.Float(), nullable=True),
    sa.Column('number_unique_opens', sa.Integer(), nullable=True),
    sa.Column('percent_unique_opens', sa.Float(), nullable=True),
    sa.Column('number_clicks', sa.Integer(), nullable=True),
    sa.Column('percent_clicks', sa.Float(), nullable=True),
    sa.Column('number_unique_clicks', sa.Integer(), nullable=True),
    sa.Column('percent_unique_clicks', sa.Float(), nullable=True),
    sa.Column('number_unsubs', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'campaign', sa.Column('is_rtm', sa.Boolean(), nullable=True))
    op.add_column(u'campaign', sa.Column('is_user_initiated', sa.Boolean(), nullable=True))
    op.add_column(u'variate_campaign_combination', sa.Column('mailchimp_id', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'variate_campaign_combination', 'mailchimp_id')
    op.drop_column(u'campaign', 'is_user_initiated')
    op.drop_column(u'campaign', 'is_rtm')
    op.drop_table('tracking')
    ### end Alembic commands ###
