"""empty message

Revision ID: 2e024608ea28
Revises: 521079e37d65
Create Date: 2016-10-27 11:56:15.237361

"""

# revision identifiers, used by Alembic.
revision = '2e024608ea28'
down_revision = '521079e37d65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
