"""empty message

Revision ID: 2e74aba94b64
Revises: 1a88c3ecf0d0
Create Date: 2016-11-10 19:57:56.353349

"""

# revision identifiers, used by Alembic.
revision = '2e74aba94b64'
down_revision = '1a88c3ecf0d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
