"""empty message

Revision ID: 2ea1cccff689
Revises: 21bf59883e1f
Create Date: 2017-01-16 08:01:25.695920

"""

# revision identifiers, used by Alembic.
revision = '2ea1cccff689'
down_revision = '21bf59883e1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_variate_detail', sa.Column('email_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tracking_variate_detail', 'email', ['email_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_variate_detail', type_='foreignkey')
    op.drop_column('tracking_variate_detail', 'email_id')
    ### end Alembic commands ###
