"""empty message

Revision ID: 3119dea179ef
Revises: 3c06919b38a4
Create Date: 2016-10-27 13:09:36.696447

"""

# revision identifiers, used by Alembic.
revision = '3119dea179ef'
down_revision = '3c06919b38a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_log', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('process_log', sa.Column('esp_data', sa.String(length=2000), nullable=True))
    op.add_column('process_log', sa.Column('esp_interaction', sa.Integer(), nullable=True))
    op.add_column('process_log', sa.Column('esp_object', sa.String(length=150), nullable=True))
    op.add_column('process_log', sa.Column('esp_object_key', sa.String(length=40), nullable=True))
    op.add_column('process_log', sa.Column('esp_object_name', sa.String(length=200), nullable=True))
    op.add_column('process_log', sa.Column('esp_operation', sa.String(length=50), nullable=True))
    op.add_column('process_log', sa.Column('tool_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'process_log', 'tool', ['tool_id'], ['id'])
    op.create_foreign_key(None, 'process_log', 'brand', ['brand_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_log', type_='foreignkey')
    op.drop_constraint(None, 'process_log', type_='foreignkey')
    op.drop_column('process_log', 'tool_id')
    op.drop_column('process_log', 'esp_operation')
    op.drop_column('process_log', 'esp_object_name')
    op.drop_column('process_log', 'esp_object_key')
    op.drop_column('process_log', 'esp_object')
    op.drop_column('process_log', 'esp_interaction')
    op.drop_column('process_log', 'esp_data')
    op.drop_column('process_log', 'brand_id')
    ### end Alembic commands ###
