"""empty message

Revision ID: 323a838f66ff
Revises: 1b6a9c3796d7
Create Date: 2016-11-04 08:50:46.767033

"""

# revision identifiers, used by Alembic.
revision = '323a838f66ff'
down_revision = '1b6a9c3796d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_delimiter', sa.String(length=1), nullable=True),
    sa.Column('target_type', sa.String(length=200), nullable=True),
    sa.Column('import_type', sa.Integer(), nullable=True),
    sa.Column('system_definition', sa.Boolean(), nullable=True),
    sa.Column('notify_addresses', sa.String(length=1024), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('overall_status', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.String(length=2000), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_actvity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_definition_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('inserted', sa.Integer(), nullable=True),
    sa.Column('ignored', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['import_definition_id'], ['import_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_field_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_definition_id', sa.Integer(), nullable=True),
    sa.Column('source_field', sa.String(length=100), nullable=True),
    sa.Column('destination_field', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['import_definition_id'], ['import_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_field_mapping')
    op.drop_table('import_actvity')
    op.drop_table('system_job')
    op.drop_table('import_definition')
    ### end Alembic commands ###
