"""empty message

Revision ID: 33d71da9ce8e
Revises: 2513dc22a5eb
Create Date: 2016-11-07 11:19:22.284809

"""

# revision identifiers, used by Alembic.
revision = '33d71da9ce8e'
down_revision = '2513dc22a5eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_actvity', sa.Column('errors', sa.Integer(), nullable=True))
    op.add_column('import_actvity', sa.Column('inserts', sa.Integer(), nullable=True))
    op.add_column('import_actvity', sa.Column('updates', sa.Integer(), nullable=True))
    op.drop_column('import_actvity', 'errored')
    op.drop_column('import_actvity', 'inserted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_actvity', sa.Column('inserted', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('import_actvity', sa.Column('errored', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('import_actvity', 'updates')
    op.drop_column('import_actvity', 'inserts')
    op.drop_column('import_actvity', 'errors')
    ### end Alembic commands ###
