"""empty message

Revision ID: 35e73b38e0f8
Revises: 165a1f2d1cb7
Create Date: 2016-12-27 11:25:24.463193

"""

# revision identifiers, used by Alembic.
revision = '35e73b38e0f8'
down_revision = '165a1f2d1cb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variate_campaign', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('variate_campaign', sa.Column('email_id', sa.Integer(), nullable=True))
    op.add_column('variate_campaign', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('variate_campaign', sa.Column('from_name', sa.String(length=200), nullable=True))
    op.add_column('variate_campaign', sa.Column('list_id', sa.Integer(), nullable=True))
    op.add_column('variate_campaign', sa.Column('mailchimp_id', sa.String(length=100), nullable=True))
    op.add_column('variate_campaign', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('variate_campaign', sa.Column('reply_to', sa.String(length=200), nullable=True))
    op.add_column('variate_campaign', sa.Column('schedule_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('variate_campaign', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.add_column('variate_campaign', sa.Column('send_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('variate_campaign', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('variate_campaign', sa.Column('subject_line', sa.String(length=200), nullable=True))
    op.add_column('variate_campaign', sa.Column('test_type', sa.String(), nullable=True))
    op.drop_constraint(u'variate_campaign_campaign_id_fkey', 'variate_campaign', type_='foreignkey')
    op.create_foreign_key(None, 'variate_campaign', 'email', ['email_id'], ['id'])
    op.create_foreign_key(None, 'variate_campaign', 'folder', ['folder_id'], ['id'])
    op.create_foreign_key(None, 'variate_campaign', 'brand', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'variate_campaign', 'list', ['list_id'], ['id'])
    op.create_foreign_key(None, 'variate_campaign', 'segment', ['segment_id'], ['id'])
    op.drop_column('variate_campaign', 'campaign_id')
    op.add_column('variate_campaign_combination', sa.Column('email_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'variate_campaign_combination', 'email', ['email_id'], ['id'])
    op.drop_column('variate_campaign_combination', 'content_label')
    op.drop_column('variate_campaign_combination', 'plain_text_content')
    op.drop_column('variate_campaign_combination', 'html_content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variate_campaign_combination', sa.Column('html_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('variate_campaign_combination', sa.Column('plain_text_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('variate_campaign_combination', sa.Column('content_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'variate_campaign_combination', type_='foreignkey')
    op.drop_column('variate_campaign_combination', 'email_id')
    op.add_column('variate_campaign', sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'variate_campaign', type_='foreignkey')
    op.drop_constraint(None, 'variate_campaign', type_='foreignkey')
    op.drop_constraint(None, 'variate_campaign', type_='foreignkey')
    op.drop_constraint(None, 'variate_campaign', type_='foreignkey')
    op.drop_constraint(None, 'variate_campaign', type_='foreignkey')
    op.create_foreign_key(u'variate_campaign_campaign_id_fkey', 'variate_campaign', 'campaign', ['campaign_id'], ['id'])
    op.drop_column('variate_campaign', 'test_type')
    op.drop_column('variate_campaign', 'subject_line')
    op.drop_column('variate_campaign', 'status')
    op.drop_column('variate_campaign', 'send_time')
    op.drop_column('variate_campaign', 'segment_id')
    op.drop_column('variate_campaign', 'schedule_time')
    op.drop_column('variate_campaign', 'reply_to')
    op.drop_column('variate_campaign', 'name')
    op.drop_column('variate_campaign', 'mailchimp_id')
    op.drop_column('variate_campaign', 'list_id')
    op.drop_column('variate_campaign', 'from_name')
    op.drop_column('variate_campaign', 'folder_id')
    op.drop_column('variate_campaign', 'email_id')
    op.drop_column('variate_campaign', 'brand_id')
    ### end Alembic commands ###
