"""empty message

Revision ID: 360ed1adb87a
Revises: c637c6603e5
Create Date: 2016-11-29 14:45:13.504850

"""

# revision identifiers, used by Alembic.
revision = '360ed1adb87a'
down_revision = 'c637c6603e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
