"""empty message

Revision ID: 360f3d20ca94
Revises: 4cc9e0dc5a45
Create Date: 2017-01-04 12:03:52.854143

"""

# revision identifiers, used by Alembic.
revision = '360f3d20ca94'
down_revision = '4cc9e0dc5a45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('tracking', sa.Column('updated_by', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'updated_by')
    op.drop_column('tracking', 'updated')
    ### end Alembic commands ###
