"""empty message

Revision ID: 390f2b7a921a
Revises: 323a838f66ff
Create Date: 2016-11-05 19:42:09.686136

"""

# revision identifiers, used by Alembic.
revision = '390f2b7a921a'
down_revision = '323a838f66ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_definition', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('import_definition', sa.Column('target_folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'import_definition', 'folder', ['folder_id'], ['id'])
    op.create_foreign_key(None, 'import_definition', 'folder', ['target_folder_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_definition', type_='foreignkey')
    op.drop_constraint(None, 'import_definition', type_='foreignkey')
    op.drop_column('import_definition', 'target_folder_id')
    op.drop_column('import_definition', 'folder_id')
    ### end Alembic commands ###
