"""empty message

Revision ID: 3b4b3483e5b0
Revises: d83339d9891
Create Date: 2016-12-19 11:16:39.836929

"""

# revision identifiers, used by Alembic.
revision = '3b4b3483e5b0'
down_revision = 'd83339d9891'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('schedule_time', sa.TIMESTAMP(), nullable=True))
    op.drop_column('campaign', 'list_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('list_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('campaign', 'schedule_time')
    ### end Alembic commands ###
