"""empty message

Revision ID: 3c06919b38a4
Revises: 7fc9790e865
Create Date: 2016-10-27 12:00:33.854600

"""

# revision identifiers, used by Alembic.
revision = '3c06919b38a4'
down_revision = '7fc9790e865'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    ### end Alembic commands ###
