"""empty message

Revision ID: 3c3d96641a06
Revises: 4d1ab30439a3
Create Date: 2016-11-18 09:31:37.803355

"""

# revision identifiers, used by Alembic.
revision = '3c3d96641a06'
down_revision = '4d1ab30439a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_category', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'template_category', 'folder', ['folder_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_category', type_='foreignkey')
    op.drop_column('template_category', 'folder_id')
    ### end Alembic commands ###
