"""empty message

Revision ID: 3c592affa720
Revises: 5a7a1d6b9f7a
Create Date: 2017-04-14 15:19:20.864913

"""

# revision identifiers, used by Alembic.
revision = '3c592affa720'
down_revision = '5a7a1d6b9f7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'fk_list_id', 'campaign', type_='foreignkey')
    op.create_foreign_key(None, 'campaign', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'data_view_bounce', type_='foreignkey')
    op.create_foreign_key(None, 'data_view_bounce', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'data_view_click', type_='foreignkey')
    op.create_foreign_key(None, 'data_view_click', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'data_view_open', type_='foreignkey')
    op.create_foreign_key(None, 'data_view_open', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'data_view_sent', type_='foreignkey')
    op.create_foreign_key(None, 'data_view_sent', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'data_view_unsubscribe', type_='foreignkey')
    op.create_foreign_key(None, 'data_view_unsubscribe', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'list_activity', type_='foreignkey')
    op.create_foreign_key(None, 'list_activity', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'list_campaign_default', type_='foreignkey')
    op.create_foreign_key(None, 'list_campaign_default', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'list_contact', type_='foreignkey')
    op.create_foreign_key(None, 'list_contact', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'list_merge_field', type_='foreignkey')
    op.create_foreign_key(None, 'list_merge_field', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_list_id', 'list_subscriber', type_='foreignkey')
    op.create_foreign_key(None, 'list_subscriber', 'list', ['list_id'], ['id'])
    op.drop_constraint(u'fk_campaign_id', 'list_subscriber_activity', type_='foreignkey')
    op.create_foreign_key(None, 'list_subscriber_activity', 'campaign', ['campaign_id'], ['id'])
    op.drop_constraint(u'fk_list_subscriber_id', 'list_subscriber_location', type_='foreignkey')
    op.create_foreign_key(None, 'list_subscriber_location', 'list_subscriber', ['list_subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list_subscriber_location', type_='foreignkey')
    op.create_foreign_key(u'fk_list_subscriber_id', 'list_subscriber_location', 'list_subscriber', ['list_subscriber_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'list_subscriber_activity', type_='foreignkey')
    op.create_foreign_key(u'fk_campaign_id', 'list_subscriber_activity', 'campaign', ['campaign_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'list_subscriber', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'list_subscriber', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'list_merge_field', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'list_merge_field', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'list_contact', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'list_contact', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'list_campaign_default', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'list_campaign_default', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'list_activity', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'list_activity', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'data_view_unsubscribe', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'data_view_unsubscribe', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'data_view_sent', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'data_view_sent', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'data_view_open', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'data_view_open', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'data_view_click', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'data_view_click', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'data_view_bounce', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'data_view_bounce', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.create_foreign_key(u'fk_list_id', 'campaign', 'list', ['list_id'], ['id'], ondelete=u'CASCADE')
    op.drop_table('file_location')
    # ### end Alembic commands ###
