"""empty message

Revision ID: 3df9cb62c190
Revises: 53c42b7ee80c
Create Date: 2016-11-23 10:28:02.044574

"""

# revision identifiers, used by Alembic.
revision = '3df9cb62c190'
down_revision = '53c42b7ee80c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('full_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'full_html')
    ### end Alembic commands ###
