"""empty message

Revision ID: 3f94ae249f0f
Revises: 3119dea179ef
Create Date: 2016-10-27 13:38:13.391036

"""

# revision identifiers, used by Alembic.
revision = '3f94ae249f0f'
down_revision = '3119dea179ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
