"""empty message

Revision ID: 41de8a6de4c4
Revises: 2c26bf6baff5
Create Date: 2016-10-28 07:22:14.485572

"""

# revision identifiers, used by Alembic.
revision = '41de8a6de4c4'
down_revision = '2c26bf6baff5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
