"""empty message

Revision ID: 41e88b901b25
Revises: 423f34f9a8fc
Create Date: 2016-11-22 08:23:14.192479

"""

# revision identifiers, used by Alembic.
revision = '41e88b901b25'
down_revision = '423f34f9a8fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
