"""empty message

Revision ID: 423f34f9a8fc
Revises: 3c3d96641a06
Create Date: 2016-11-21 14:58:09.795187

"""

# revision identifiers, used by Alembic.
revision = '423f34f9a8fc'
down_revision = '3c3d96641a06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_merge_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_merge_field')
    ### end Alembic commands ###
