"""empty message

Revision ID: 450ed2dc7f03
Revises: 360ed1adb87a
Create Date: 2016-11-29 14:46:07.857971

"""

# revision identifiers, used by Alembic.
revision = '450ed2dc7f03'
down_revision = '360ed1adb87a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
