"""empty message

Revision ID: 45ef001dc1ad
Revises: 477250639496
Create Date: 2016-11-08 18:30:58.811409

"""

# revision identifiers, used by Alembic.
revision = '45ef001dc1ad'
down_revision = '477250639496'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_subscriber_merge_field', sa.Column('default_value', sa.String(length=200), nullable=True))
    op.add_column('list_subscriber_merge_field', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('list_subscriber_merge_field', sa.Column('mailchimp_id', sa.Integer(), nullable=True))
    op.add_column('list_subscriber_merge_field', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('list_subscriber_merge_field', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('list_subscriber_merge_field', sa.Column('required', sa.Boolean(), nullable=True))
    op.add_column('list_subscriber_merge_field', sa.Column('tag', sa.String(length=200), nullable=True))
    op.add_column('list_subscriber_merge_field', sa.Column('type', sa.String(length=200), nullable=True))
    op.drop_column('list_subscriber_merge_field', 'var')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_subscriber_merge_field', sa.Column('var', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('list_subscriber_merge_field', 'type')
    op.drop_column('list_subscriber_merge_field', 'tag')
    op.drop_column('list_subscriber_merge_field', 'required')
    op.drop_column('list_subscriber_merge_field', 'public')
    op.drop_column('list_subscriber_merge_field', 'name')
    op.drop_column('list_subscriber_merge_field', 'mailchimp_id')
    op.drop_column('list_subscriber_merge_field', 'display_order')
    op.drop_column('list_subscriber_merge_field', 'default_value')
    ### end Alembic commands ###
