"""empty message

Revision ID: 477250639496
Revises: 2b396187cfec
Create Date: 2016-11-08 09:49:58.676501

"""

# revision identifiers, used by Alembic.
revision = '477250639496'
down_revision = '2b396187cfec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_field', sa.Column('export', sa.Boolean(), nullable=True))
    op.add_column('form_field', sa.Column('search', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_field', 'search')
    op.drop_column('form_field', 'export')
    ### end Alembic commands ###
