"""empty message

Revision ID: 47c3470b7197
Revises: 2c7802e16388
Create Date: 2017-01-03 18:47:53.139410

"""

# revision identifiers, used by Alembic.
revision = '47c3470b7197'
down_revision = '2c7802e16388'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_variate_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=True),
    sa.Column('email_name', sa.String(length=200), nullable=True),
    sa.Column('send_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('subject_line', sa.String(length=200), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('reply_to', sa.String(length=200), nullable=True),
    sa.Column('recipients', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_id'], ['tracking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'tracking', sa.Column('from_name', sa.String(length=200), nullable=True))
    op.add_column(u'tracking', sa.Column('reply_to', sa.String(length=200), nullable=True))
    op.add_column(u'tracking', sa.Column('variate_campaign_test_combinations', sa.Integer(), nullable=True))
    op.add_column(u'tracking', sa.Column('variate_campaign_test_size', sa.Integer(), nullable=True))
    op.add_column(u'tracking', sa.Column('variate_campaign_test_type', sa.String(), nullable=True))
    op.add_column(u'tracking', sa.Column('variate_campaign_wait_time', sa.Integer(), nullable=True))
    op.add_column(u'tracking', sa.Column('variate_campaign_winner_criteria', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tracking', 'variate_campaign_winner_criteria')
    op.drop_column(u'tracking', 'variate_campaign_wait_time')
    op.drop_column(u'tracking', 'variate_campaign_test_type')
    op.drop_column(u'tracking', 'variate_campaign_test_size')
    op.drop_column(u'tracking', 'variate_campaign_test_combinations')
    op.drop_column(u'tracking', 'reply_to')
    op.drop_column(u'tracking', 'from_name')
    op.drop_table('tracking_variate_detail')
    ### end Alembic commands ###
