"""empty message

Revision ID: 4ab5fe941594
Revises: 4c4c8d833886
Create Date: 2017-04-19 10:29:29.190451

"""

# revision identifiers, used by Alembic.
revision = '4ab5fe941594'
down_revision = '4c4c8d833886'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'api_log_created_by_fkey', 'api_log', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'api_log_created_by_fkey', 'api_log', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###
