"""empty message

Revision ID: 4c4c8d833886
Revises: cf975d3bd023
Create Date: 2017-04-19 10:25:59.651986

"""

# revision identifiers, used by Alembic.
revision = '4c4c8d833886'
down_revision = 'cf975d3bd023'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'api_log', 'user', ['created_by'], ['id'])
    op.drop_constraint(u'user_password_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'user_password_key', 'user', ['password'])
    op.drop_constraint(None, 'api_log', type_='foreignkey')
    # ### end Alembic commands ###
