"""empty message

Revision ID: 4d1ab30439a3
Revises: 1940737b99e1
Create Date: 2016-11-17 22:01:09.748536

"""

# revision identifiers, used by Alembic.
revision = '4d1ab30439a3'
down_revision = '1940737b99e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_section', sa.Column('default_content', sa.Text(), nullable=True))
    op.add_column('template_section', sa.Column('tag', sa.String(length=100), nullable=True))
    op.drop_column('template_section', 'section')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_section', sa.Column('section', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('template_section', 'tag')
    op.drop_column('template_section', 'default_content')
    ### end Alembic commands ###
