"""empty message

Revision ID: 521079e37d65
Revises: 1981b84e7308
Create Date: 2016-10-27 11:51:22.781259

"""

# revision identifiers, used by Alembic.
revision = '521079e37d65'
down_revision = '1981b84e7308'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deluge_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('magnet', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('started', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'download_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'download_pkey')
    )
    ### end Alembic commands ###
