"""empty message

Revision ID: 540cb079587e
Revises: 35e73b38e0f8
Create Date: 2016-12-27 13:09:26.296183

"""

# revision identifiers, used by Alembic.
revision = '540cb079587e'
down_revision = '35e73b38e0f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variate_campaign', sa.Column('test_combinations', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variate_campaign', 'test_combinations')
    ### end Alembic commands ###
