"""empty message

Revision ID: 5a7a1d6b9f7a
Revises: 25ebcd646361
Create Date: 2017-01-26 07:33:56.578612

"""

# revision identifiers, used by Alembic.
revision = '5a7a1d6b9f7a'
down_revision = '25ebcd646361'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('html_by', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'html_by')
    ### end Alembic commands ###
