"""empty message

Revision ID: 66762a8fb29
Revises: 33d71da9ce8e
Create Date: 2016-11-07 12:11:49.304477

"""

# revision identifiers, used by Alembic.
revision = '66762a8fb29'
down_revision = '33d71da9ce8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_delimiter', sa.String(length=1), nullable=True),
    sa.Column('target_type', sa.String(length=200), nullable=True),
    sa.Column('target_folder_id', sa.Integer(), nullable=True),
    sa.Column('export_type', sa.Integer(), nullable=True),
    sa.Column('system_definition', sa.Boolean(), nullable=True),
    sa.Column('notify_addresses', sa.String(length=1024), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['target_folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_actvity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_definition_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['export_definition_id'], ['export_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_definition_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=200), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['export_definition_id'], ['export_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_definition_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['export_definition_id'], ['export_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_object')
    op.drop_table('export_field')
    op.drop_table('export_actvity')
    op.drop_table('export_definition')
    ### end Alembic commands ###
