"""empty message

Revision ID: 73820953f23
Revises: 540cb079587e
Create Date: 2016-12-27 13:12:55.617807

"""

# revision identifiers, used by Alembic.
revision = '73820953f23'
down_revision = '540cb079587e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_subscriber_activity', sa.Column('variate_campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'list_subscriber_activity', 'variate_campaign', ['variate_campaign_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list_subscriber_activity', type_='foreignkey')
    op.drop_column('list_subscriber_activity', 'variate_campaign_id')
    ### end Alembic commands ###
