"""empty message

Revision ID: 7fc9790e865
Revises: 15c856b95850
Create Date: 2016-10-27 11:59:32.313771

"""

# revision identifiers, used by Alembic.
revision = '7fc9790e865'
down_revision = '15c856b95850'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isadmin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isadmin', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
