"""empty message

Revision ID: a27dc7418cb
Revises: c6a2eb47c45
Create Date: 2016-11-09 07:27:26.354993

"""

# revision identifiers, used by Alembic.
revision = 'a27dc7418cb'
down_revision = 'c6a2eb47c45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_subscriber_merge_field', sa.Column('list_merge_field_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'list_subscriber_merge_field', 'list_merge_field', ['list_merge_field_id'], ['id'])
    op.drop_column('list_subscriber_merge_field', 'list_merge_field_tag')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_subscriber_merge_field', sa.Column('list_merge_field_tag', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'list_subscriber_merge_field', type_='foreignkey')
    op.drop_column('list_subscriber_merge_field', 'list_merge_field_id')
    ### end Alembic commands ###
