"""empty message

Revision ID: c1553712760
Revises: 47c3470b7197
Create Date: 2017-01-04 07:51:50.737107

"""

# revision identifiers, used by Alembic.
revision = 'c1553712760'
down_revision = '47c3470b7197'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.drop_column('tracking', 'updated')
    op.drop_column('tracking', 'updated_by')
    op.add_column('tracking_variate_detail', sa.Column('is_winner', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_variate_detail', 'is_winner')
    op.add_column('tracking', sa.Column('updated_by', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('tracking', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tracking', 'campaign_id')
    ### end Alembic commands ###
