"""empty message

Revision ID: c28715c9232
Revises: 2603810e861d
Create Date: 2016-12-14 13:00:58.502078

"""

# revision identifiers, used by Alembic.
revision = 'c28715c9232'
down_revision = '2603810e861d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_segment_condition')
    op.add_column('campaign', sa.Column('ds_emails_canceled', sa.Integer(), nullable=True))
    op.add_column('campaign', sa.Column('ds_emails_sent', sa.Integer(), nullable=True))
    op.drop_column('campaign', 'emails_canceled')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('emails_canceled', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('campaign', 'ds_emails_sent')
    op.drop_column('campaign', 'ds_emails_canceled')
    op.create_table('campaign_segment_condition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('op', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('field', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], [u'campaign.id'], name=u'campaign_segment_condition_campaign_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'campaign_segment_condition_pkey')
    )
    ### end Alembic commands ###
