"""empty message

Revision ID: c637c6603e5
Revises: 3df9cb62c190
Create Date: 2016-11-28 14:59:54.793536

"""

# revision identifiers, used by Alembic.
revision = 'c637c6603e5'
down_revision = '3df9cb62c190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'email_section_template_section_id_fkey', 'email_section', type_='foreignkey')
    op.drop_column('email_section', 'template_section_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_section', sa.Column('template_section_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'email_section_template_section_id_fkey', 'email_section', 'template_section', ['template_section_id'], ['id'])
    ### end Alembic commands ###
