"""empty message

Revision ID: c6a2eb47c45
Revises: 45ef001dc1ad
Create Date: 2016-11-09 07:16:37.091476

"""

# revision identifiers, used by Alembic.
revision = 'c6a2eb47c45'
down_revision = '45ef001dc1ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_merge_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'list_subscriber_merge_field', sa.Column('list_merge_field_tag', sa.String(length=20), nullable=True))
    #op.create_foreign_key(None, 'list_subscriber_merge_field', 'list_merge_field', ['list_merge_field_id'], ['id'])
    op.drop_column(u'list_subscriber_merge_field', 'default_value')
    op.drop_column(u'list_subscriber_merge_field', 'name')
    op.drop_column(u'list_subscriber_merge_field', 'display_order')
    op.drop_column(u'list_subscriber_merge_field', 'required')
    op.drop_column(u'list_subscriber_merge_field', 'tag')
    op.drop_column(u'list_subscriber_merge_field', 'type')
    op.drop_column(u'list_subscriber_merge_field', 'public')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'list_subscriber_merge_field', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(u'list_subscriber_merge_field', sa.Column('type', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column(u'list_subscriber_merge_field', sa.Column('tag', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column(u'list_subscriber_merge_field', sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(u'list_subscriber_merge_field', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'list_subscriber_merge_field', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column(u'list_subscriber_merge_field', sa.Column('default_value', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'list_subscriber_merge_field', type_='foreignkey')
    op.drop_column(u'list_subscriber_merge_field', 'list_merge_field_tag')
    op.drop_table('list_merge_field')
    ### end Alembic commands ###
