"""empty message

Revision ID: cf975d3bd023
Revises: 3c592affa720
Create Date: 2017-04-14 15:32:59.161379

"""

# revision identifiers, used by Alembic.
revision = 'cf975d3bd023'
down_revision = '3c592affa720'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
