"""empty message

Revision ID: d01554b9f592
Revises: 4ab5fe941594
Create Date: 2017-04-20 10:37:53.543466

"""

# revision identifiers, used by Alembic.
revision = 'd01554b9f592'
down_revision = '4ab5fe941594'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_location', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('file_location', sa.Column('external_host', sa.String(length=50), nullable=True))
    op.add_column('file_location', sa.Column('external_pass', sa.String(length=50), nullable=True))
    op.add_column('file_location', sa.Column('external_path', sa.String(length=2000), nullable=True))
    op.add_column('file_location', sa.Column('external_user', sa.String(length=50), nullable=True))
    op.add_column('file_location', sa.Column('internal_location', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'file_location', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_location', type_='unique')
    op.drop_column('file_location', 'internal_location')
    op.drop_column('file_location', 'external_user')
    op.drop_column('file_location', 'external_path')
    op.drop_column('file_location', 'external_pass')
    op.drop_column('file_location', 'external_host')
    op.drop_column('file_location', 'brand_id')
    # ### end Alembic commands ###
