"""empty message

Revision ID: d83339d9891
Revises: 2b99dfcf82ab
Create Date: 2016-12-14 15:26:02.582912

"""

# revision identifiers, used by Alembic.
revision = 'd83339d9891'
down_revision = '2b99dfcf82ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
