"""empty message

Revision ID: fa5949db6b87
Revises: d01554b9f592
Create Date: 2017-04-20 12:05:28.311999

"""

# revision identifiers, used by Alembic.
revision = 'fa5949db6b87'
down_revision = 'd01554b9f592'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'file_location_name_key', 'file_location', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'file_location_name_key', 'file_location', ['name'])
    # ### end Alembic commands ###
